import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from 'react';
import { useTranslation } from 'react-i18next';
import { Activity, Brain, Button, Flame, Heart, Menu, Moon, Search, User, Wind } from '../../components/ui';
import { AdminDrawer } from '../admin/AdminDrawer';
import { Situation } from '../../types';
const ExerciseCard = ({ exercise, onClick }) => {
    const { t } = useTranslation(['common']);
    const getIcon = () => {
        if (exercise.situation.includes(Situation.Crisis))
            return _jsx(Activity, { className: "w-5 h-5 text-rose-500" });
        if (exercise.situation.includes(Situation.Sleep))
            return _jsx(Moon, { className: "w-5 h-5 text-indigo-500" });
        if (exercise.situation.includes(Situation.Anger))
            return _jsx(Flame, { className: "w-5 h-5 text-orange-500" });
        return _jsx(Wind, { className: "w-5 h-5 text-teal-500" });
    };
    return (_jsxs("div", { onClick: onClick, className: "group bg-white rounded-xl shadow-sm hover:shadow-md transition-all cursor-pointer overflow-hidden border border-gray-100 flex flex-col h-full", children: [_jsxs("div", { className: "relative h-32 overflow-hidden bg-gray-100", children: [_jsx("img", { src: exercise.imageUrl, alt: exercise.title, className: "w-full h-full object-cover group-hover:scale-105 transition-transform duration-300", onError: (e) => { e.target.src = 'https://placehold.co/600x400/e2e8f0/94a3b8?text=NeuroSooth'; } }), _jsxs("div", { className: "absolute top-2 right-2 bg-white/90 backdrop-blur-sm px-2 py-1 rounded-md text-xs font-semibold text-slate-700 flex items-center gap-1", children: [_jsx(Heart, { className: "w-3 h-3 text-rose-500 fill-rose-500" }), " ", exercise.thanksCount] })] }), _jsxs("div", { className: "p-4 flex-1 flex flex-col", children: [_jsxs("div", { className: "flex items-start justify-between mb-2", children: [_jsx("h3", { className: "font-semibold text-slate-900 leading-tight group-hover:text-teal-700 transition-colors", children: exercise.title }), getIcon()] }), _jsx("p", { className: "text-sm text-slate-500 mb-4 line-clamp-2 flex-1", children: exercise.description }), _jsx("div", { className: "flex flex-wrap gap-1 mt-auto", children: exercise.tags.slice(0, 2).map(tag => (_jsx("span", { className: "text-[10px] uppercase tracking-wider font-bold text-slate-400 bg-slate-100 px-2 py-1 rounded", children: tag }, tag))) })] })] }));
};
export const Dashboard = ({ user, exercises, situationFilter, onFilterChange, onExerciseClick, onAddTechnique, onPartnerAccess, syncStatus, showSyncStatus, partnerSession, isAdminMenuOpen, onOpenAdminMenu, onCloseAdminMenu }) => {
    const { t } = useTranslation(['common', 'dashboard']);
    return (_jsxs("div", { className: "min-h-screen bg-slate-50", children: [_jsxs("header", { className: "bg-white shadow-sm sticky top-0 z-20", children: [_jsxs("div", { className: "max-w-6xl mx-auto px-4 py-4 flex justify-between items-center", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("div", { className: "bg-teal-600 p-1.5 rounded-lg", children: _jsx(Brain, { className: "w-6 h-6 text-white" }) }), _jsx("span", { className: "font-bold text-xl text-slate-800 hidden md:block", children: t('app.name') })] }), _jsxs("div", { className: "flex items-center gap-3", children: [user && (_jsxs("div", { className: "flex items-center gap-2 text-sm text-slate-600 bg-slate-100 px-3 py-1.5 rounded-full", children: [_jsx(User, { className: "w-4 h-4" }), _jsx("span", { className: "font-medium", children: user.name })] })), _jsxs("button", { type: "button", onClick: onOpenAdminMenu, "aria-label": "Ouvrir le menu administrateur", "aria-expanded": isAdminMenuOpen, className: "w-10 h-10 rounded-full border border-slate-200 flex items-center justify-center text-slate-600 hover:text-slate-900 hover:bg-slate-50", children: [_jsx(Menu, { className: "w-5 h-5" }), _jsx("span", { className: "sr-only", children: t('menu.adminSpace') })] })] })] }), _jsx("div", { className: "border-t border-gray-100 overflow-x-auto hide-scrollbar", children: _jsxs("div", { className: "max-w-6xl mx-auto px-4 py-3 flex gap-2 min-w-max", children: [_jsx("button", { onClick: () => onFilterChange('All'), className: `px-4 py-1.5 rounded-full text-sm font-medium transition-colors ${situationFilter === 'All'
                                        ? 'bg-slate-800 text-white'
                                        : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'}`, children: t('labels.all') }), Object.values(Situation).map((sit) => (_jsx("button", { onClick: () => onFilterChange(sit), className: `px-4 py-1.5 rounded-full text-sm font-medium transition-colors whitespace-nowrap ${situationFilter === sit
                                        ? 'bg-teal-600 text-white shadow-md transform scale-105'
                                        : 'bg-white text-slate-600 border border-slate-200 hover:bg-slate-50'}`, children: t(`situations.${sit}`) }, sit)))] }) })] }), _jsxs("main", { className: "max-w-6xl mx-auto px-4 py-6", children: [_jsxs("div", { className: "mb-6", children: [_jsx("h2", { className: "text-2xl font-bold text-slate-900", children: situationFilter === 'All' ? t('dashboard.recommendedForYou') : t(`situations.${situationFilter}`) }), _jsx("p", { className: "text-slate-500", children: situationFilter === 'All'
                                    ? t('dashboard.basedOnProfile', { neurotypes: user?.neurotypes.map(nt => t(`neuroTypes.${nt}`)).join(', ') || '' })
                                    : t('dashboard.specificTechniques') })] }), exercises.length > 0 ? (_jsx("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 pb-20", children: exercises.map((ex) => (_jsx(ExerciseCard, { exercise: ex, onClick: () => onExerciseClick(ex) }, ex.id))) })) : (_jsxs("div", { className: "text-center py-20", children: [_jsx("div", { className: "bg-slate-100 rounded-full w-16 h-16 flex items-center justify-center mx-auto mb-4", children: _jsx(Search, { className: "w-8 h-8 text-slate-400" }) }), _jsx("h3", { className: "text-lg font-medium text-slate-900", children: t('dashboard.noTechniquesFound') }), _jsx("p", { className: "text-slate-500 mb-6", children: t('dashboard.tryChangeFilter') }), _jsxs("div", { className: "flex justify-center gap-4", children: [_jsx(Button, { variant: "outline", onClick: () => onFilterChange('All'), children: t('buttons.viewAll') }), _jsx(Button, { variant: "primary", onClick: onAddTechnique, children: t('buttons.addTechnique') })] })] }))] }), _jsx(AdminDrawer, { isOpen: isAdminMenuOpen, onClose: onCloseAdminMenu, onAddTechnique: onAddTechnique, onPartnerAccess: onPartnerAccess, syncStatus: syncStatus, showSyncStatus: showSyncStatus, partnerSession: partnerSession })] }));
};
