export const SUBSCALE_LABELS: Record<"en" | "fr", Record<string, string>> = {
  "en": {
    "Executive": "Executive Function",
    "Sequencing": "Sequencing & Order",
    "AdhdMemory": "Working memory",
    "Initiation": "Task Initiation",
    "MotorAgitation": "Motor Agitation",
    "Restlessness": "Internal Restlessness",
    "Attention": "Sustained Attention",
    "AuditoryProc": "Auditory Processing",
    "Distraction": "Distractibility",
    "Inhibition": "Inhibition Control",
    "Regulation": "Emotional Regulation",
    "Verbal": "Verbal Hyperactivity",
    "Impulsivity": "Impulsivity",
    "Timing": "Timing & Waiting",
    "Compensation": "Social Compensation",
    "Masking": "Masking Strategies",
    "Assimilation": "Social Assimilation",
    "Sensory": "Sensory Sensitivity",
    "Predictability": "Predictability Needs",
    "Energy": "Social Energy Cost",
    "Laterality": "Left/Right Laterality",
    "Visuospatial": "Visuospatial Processing",
    "Phonological": "Phonological Processing",
    "VisualProc": "Visual Processing speed",
    "DysMemory": "Verbal & Sequential Memory",
    "Effort": "Reading Effort",
    "Spelling": "Orthographic Coding",
    "Graphomotor": "Graphomotor Skills",
    "Organization": "Temporal Organization",
    "Accuracy": "Clerical Accuracy",
    "WrittenLoad": "Written Load Sensitivity",
    "AdminFriction": "Administrative Friction",
    "VerbalPref": "Verbal Preference",
    "child_FineMotor": "Childhood Fine Motor",
    "child_GrossMotor": "Childhood Gross Motor",
    "child_Main": "Childhood Coordination",
    "adult_GrossMotor": "Adult Gross Motor",
    "adult_Planning": "Motor Planning (Praxis)",
    "adult_FineMotor": "Adult Fine Motor",
    "ExecutionGap": "Idea-Action Gap",
    "PhysicalFatigue": "Physical Fatigue",
    "NumberSense": "Core Number Sense",
    "Subitizing": "Subitizing Ability",
    "WorkingMemory": "Working Memory (Math)",
    "Estimation": "Estimation",
    "Retrieval": "Fact Retrieval",
    "Arithmetic": "Arithmetic Operations",
    "Symbols": "Symbol Recognition",
    "Functional": "Functional Numeracy",
    "Anxiety": "Math Anxiety",
    "MentalMath": "Mental Math",
    "MathMemory": "Numerical Memory",
    "TimeMoney": "Time & Money Abstraction",
    "Financial": "Financial Load",
    "Mood": "Mood",
    "Injury": "Head injury history",
    "Neurology": "Neurological context",
    "Crisis": "Current distress"
  },
  "fr": {
    "Executive": "Fonctions Exécutives",
    "Sequencing": "Séquençage & Ordre",
    "AdhdMemory": "Mémoire de travail",
    "Initiation": "Initiation de Tâche",
    "MotorAgitation": "Agitation Motrice",
    "Restlessness": "Agitation Interne",
    "Attention": "Attention Soutenue",
    "AuditoryProc": "Traitement Auditif",
    "Distraction": "Distractibilité",
    "Inhibition": "Contrôle de l'Inhibition",
    "Regulation": "Régulation Émotionnelle",
    "Verbal": "Hyperactivité Verbale",
    "Impulsivity": "Impulsivité",
    "Timing": "Timing & Attente",
    "Compensation": "Compensation Sociale",
    "Masking": "Stratégies de Masquage",
    "Assimilation": "Assimilation Sociale",
    "Sensory": "Hypersensibilité Sensorielle",
    "Predictability": "Besoin de Prédictibilité",
    "Energy": "Coût Énergétique Social",
    "Laterality": "Latéralité Gauche/Droite",
    "Visuospatial": "Traitement Visuospatial",
    "Phonological": "Traitement Phonologique",
    "VisualProc": "Vitesse de Traitement Visuel",
    "DysMemory": "Mémoire Verbale & Séquentielle",
    "Effort": "Effort de Lecture",
    "Spelling": "Codage Orthographique",
    "Graphomotor": "Graphomotricité (Écriture)",
    "Organization": "Organisation Temporelle",
    "Accuracy": "Précision Administrative",
    "WrittenLoad": "Sensibilité à la Charge Écrite",
    "AdminFriction": "Friction Administrative",
    "VerbalPref": "Préférence Verbale",
    "child_FineMotor": "Motricité Fine (Enfance)",
    "child_GrossMotor": "Motricité Globale (Enfance)",
    "child_Main": "Coordination (Enfance)",
    "adult_GrossMotor": "Motricité Globale (Adulte)",
    "adult_Planning": "Planification Motrice",
    "adult_FineMotor": "Motricité Fine (Adulte)",
    "ExecutionGap": "Décalage Idée-Action",
    "PhysicalFatigue": "Fatigue Physique",
    "NumberSense": "Sens du Nombre",
    "Subitizing": "Capacité de Subitisation",
    "WorkingMemory": "Mémoire de Travail (Maths)",
    "Estimation": "Estimation",
    "Retrieval": "Récupération des Faits",
    "Arithmetic": "Opérations Arithmétiques",
    "Symbols": "Reconnaissance des Symboles",
    "Functional": "Calcul Fonctionnel",
    "Anxiety": "Anxiété Mathématique",
    "MentalMath": "Calcul Mental",
    "MathMemory": "Mémoire Numérique",
    "TimeMoney": "Abstraction Temps & Argent",
    "Financial": "Charge Cognitive Financière",
    "Mood": "Humeur",
    "Injury": "Antécédents de blessure à la tête",
    "Neurology": "Contexte neurologique",
    "Crisis": "Détresse actuelle"
  }
};
