import { Exercise, NeuroType, Situation, SupportNeed } from './types.js';

export const INITIAL_EXERCISES: Exercise[] = [
  {
    id: 'resp-478',
    title: 'Respiration 4-7-8',
    description: 'Une respiration rythmée qui peut aider certaines personnes à ralentir et à préparer le sommeil.',
    situation: [Situation.Sleep, Situation.Rumination, Situation.Stress],
    neurotypes: [NeuroType.ADHD, NeuroType.Trauma, NeuroType.ASD],
    duration: '2-5 minutes',
    steps: [
      'Inspirez par le nez doucement pendant 4 secondes.',
      'Si cela reste confortable, marquez une pause pendant 7 secondes.',
      'Expirez bruyamment par la bouche pendant 8 secondes.',
      'Répétez le cycle 4 fois.'
    ],
    warning: 'Respirez sans forcer. Réduisez les temps ou arrêtez en cas de vertige, d’essoufflement ou d’inconfort.',
    imageUrl: '/images/exercises/resp-478.svg',
    tags: ['Respiration', 'Vagal', 'Sommeil'],
    supportNeeds: [SupportNeed.Recovery, SupportNeed.SensoryRegulation],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'ice-dive',
    title: 'Compresse fraîche sur le visage',
    description: 'Une stimulation fraîche et brève peut offrir un repère sensoriel pendant une montée de stress.',
    situation: [Situation.Crisis, Situation.Anger],
    neurotypes: [NeuroType.Trauma, NeuroType.ASD],
    duration: '30 secondes',
    steps: [
      'Enveloppez une poche fraîche dans un linge ; ne posez jamais de glace directement sur la peau.',
      'Asseyez-vous dans un endroit sûr et continuez à respirer normalement.',
      'Posez doucement la compresse sur les joues et le haut du visage pendant quelques secondes.',
      'Retirez-la, vérifiez vos sensations, puis répétez seulement si cela reste confortable.'
    ],
    warning: 'N’immergez pas le visage et ne bloquez pas votre respiration. Évitez cette pratique en cas de problème cardiaque ou circulatoire, de malaise, d’intolérance au froid ou d’avis médical contraire.',
    imageUrl: '/images/exercises/ice-dive.svg',
    tags: ['Urgence', 'Bio-hack', 'Froid'],
    supportNeeds: [SupportNeed.SensoryRegulation, SupportNeed.Recovery],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'wall-push',
    title: 'La Poussée Murale',
    description: 'Une poussée contrôlée qui peut aider à mobiliser la tension et à retrouver des appuis corporels.',
    situation: [Situation.Anger, Situation.Stress],
    neurotypes: [NeuroType.ADHD, NeuroType.Trauma],
    duration: '1-2 minutes',
    steps: [
      'Mettez-vous face à un mur solide en fente (une jambe devant).',
      'Posez les mains à plat et augmentez progressivement la poussée sans aller jusqu’à la douleur.',
      'Engagez les abdos et les jambes.',
      'Visualisez que vous repoussez une menace ou une injustice.',
      'Relâchez quand les muscles tremblent et sentez l\'espace créé.'
    ],
    warning: 'Arrêtez en cas de douleur, de vertige ou de difficulté à respirer. Adaptez l’effort à vos capacités physiques.',
    imageUrl: '/images/exercises/wall-push.svg',
    tags: ['Décharge', 'Colère', 'Proprioception'],
    supportNeeds: [SupportNeed.Movement, SupportNeed.SensoryRegulation],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'butterfly-hug',
    title: 'Le Câlin Papillon',
    description: 'Un auto-tapotement bilatéral doux qui peut soutenir l’apaisement et le sentiment de sécurité.',
    situation: [Situation.Crisis, Situation.Stress, Situation.Trauma],
    neurotypes: [NeuroType.Trauma, NeuroType.ASD],
    duration: '2-3 minutes',
    steps: [
      'Croisez les bras sur la poitrine.',
      'Posez vos mains sur vos épaules ou bras opposés.',
      'Tapotez alternativement gauche/droite doucement, comme le battement d\'ailes d\'un papillon.',
      'Respirez lentement et profondément.',
      'Observez vos sensations sans jugement.'
    ],
    warning: 'Ralentissez ou arrêtez si le tapotement augmente la détresse, la dissociation ou des souvenirs difficiles.',
    imageUrl: '/images/exercises/butterfly-hug.svg',
    tags: ['EMDR', 'Sécurité', 'Toucher'],
    supportNeeds: [SupportNeed.SensoryRegulation, SupportNeed.Recovery],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'shaking',
    title: 'Secousses volontaires douces',
    description: 'Un mouvement volontaire léger pour explorer la tension corporelle et revenir progressivement au calme.',
    situation: [Situation.Freeze, Situation.Stress],
    neurotypes: [NeuroType.Trauma, NeuroType.ADHD],
    duration: '1-3 minutes',
    steps: [
      'Debout, commencez par secouer les mains.',
      'Secouez les bras, les épaules, faites rebondir les talons.',
      'Faites le son "Brrr" avec les lèvres.',
      'Gardez des mouvements volontaires, légers et faciles à interrompre.',
      'Ralentissez progressivement, puis observez vos appuis et votre respiration.'
    ],
    warning: 'Arrêtez si vous vous sentez submergé, dissocié, étourdi ou douloureux. Cette pratique ne remplace pas un accompagnement professionnel du trauma.',
    imageUrl: '/images/exercises/shaking.svg',
    tags: ['Somatique', 'Mouvement', 'Ancrage'],
    supportNeeds: [SupportNeed.Movement, SupportNeed.MotorPlanning],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'physio-sigh',
    title: 'Soupir physiologique',
    description: 'Une double inspiration suivie d’une longue expiration qui peut aider à réduire brièvement l’activation physiologique.',
    situation: [Situation.Stress, Situation.Crisis, Situation.Focus],
    neurotypes: [NeuroType.ADHD, NeuroType.HighSensitivity],
    duration: '1 minute',
    steps: [
      'Prenez une inspiration profonde par le nez.',
      'À la fin de l\'inspiration, reprenez une petite inspiration sèche par le nez (pour gonfler les alvéoles).',
      'Expirez très longuement par la bouche.',
      'Répétez 3 à 5 fois.'
    ],
    warning: 'Pratiquez assis et sans forcer. Arrêtez en cas de vertige, de douleur ou d’essoufflement.',
    imageUrl: '/images/exercises/physio-sigh.svg',
    tags: ['Respiration', 'Science', 'Rapide'],
    supportNeeds: [SupportNeed.Focus, SupportNeed.Recovery],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: '54321',
    title: 'Ancrage 5-4-3-2-1',
    description: 'Une exploration sensorielle pour ramener doucement l’attention vers l’environnement présent.',
    situation: [Situation.Freeze, Situation.Crisis],
    neurotypes: [NeuroType.Trauma, NeuroType.ASD],
    duration: '2 minutes',
    steps: [
      'Nommez 5 choses que vous voyez.',
      'Nommez 4 choses que vous pouvez toucher (textures).',
      'Nommez 3 choses que vous entendez.',
      'Nommez 2 choses que vous sentez (olfaction).',
      'Nommez 1 chose que vous pouvez goûter.'
    ],
    imageUrl: '/images/exercises/54321.svg',
    tags: ['Cognitif', 'Sensoriel', 'Dissociation'],
    supportNeeds: [SupportNeed.SensoryRegulation, SupportNeed.Focus],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'voo-sound',
    title: 'Le Son "Voo"',
    description: 'Une expiration sonore et prolongée dont la vibration peut soutenir une sensation d’apaisement.',
    situation: [Situation.Freeze, Situation.Stress],
    neurotypes: [NeuroType.Trauma, NeuroType.ASD],
    duration: '2 minutes',
    steps: [
      'Inspirez profondément.',
      'À l\'expiration, faites un son grave "Voooo" (comme une corne de brume).',
      'Faites vibrer la poitrine et le ventre.',
      'Attendez que l\'inspiration revienne d\'elle-même.',
      'Répétez 3 à 5 fois.'
    ],
    warning: 'Le son doit rester confortable. Arrêtez en cas de vertige, de douleur, de gêne respiratoire ou vocale.',
    imageUrl: '/images/exercises/voo-sound.svg',
    tags: ['Vagal', 'Son', 'Vibration'],
    supportNeeds: [SupportNeed.SensoryRegulation, SupportNeed.Recovery],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'psoas-release',
    title: 'Repos Constructif (Psoas)',
    description: 'Une position de repos qui peut réduire la tension perçue dans le bas du dos et autour des hanches.',
    situation: [Situation.Pain, Situation.Stress, Situation.Sleep],
    neurotypes: [NeuroType.Trauma, NeuroType.ADHD],
    duration: '10-15 minutes',
    steps: [
      'Allongez-vous sur le dos.',
      'Pliez les genoux à 90 degrés, pieds à plat au sol écartés à la largeur des hanches.',
      'Ou posez les mollets sur une chaise.',
      'Laissez la gravité faire fondre le bas du dos dans le sol.',
      'Ne faites rien d\'autre (pas de téléphone).'
    ],
    warning: 'Changez de position ou arrêtez en cas de douleur, d’engourdissement ou d’inconfort. Demandez un avis professionnel pour une douleur persistante.',
    imageUrl: '/images/exercises/psoas-release.svg',
    tags: ['Douleur', 'Posture', 'Détente'],
    supportNeeds: [SupportNeed.Recovery, SupportNeed.MotorPlanning],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'brain-dump',
    title: 'Décharge Mentale (Brain Dump)',
    description: 'Mettre les pensées sur papier peut libérer de l’espace mental et aider à prendre du recul sur les ruminations.',
    situation: [Situation.Rumination, Situation.Focus],
    neurotypes: [NeuroType.ADHD, NeuroType.ASD],
    duration: '5 minutes',
    steps: [
      'Prenez un papier et un crayon.',
      'Écrivez tous les mots, tâches, ou pensées en vrac, sans structure.',
      'Dessinez le chaos si les mots manquent.',
      'Une fois sur papier, dites à votre cerveau : "C\'est noté, tu peux lâcher".'
    ],
    imageUrl: '/images/exercises/brain-dump.svg',
    tags: ['Cognitif', 'Organisation', 'Écriture'],
    supportNeeds: [SupportNeed.WorkingMemory, SupportNeed.Organization, SupportNeed.TaskInitiation],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'visual-countdown',
    title: 'Compte à Rebours Visuel',
    description: 'Un point d’attention répétitif qui peut aider à se détourner doucement des pensées envahissantes avant le sommeil.',
    situation: [Situation.Sleep, Situation.Rumination],
    neurotypes: [NeuroType.ADHD, NeuroType.HighSensitivity],
    duration: 'Variable',
    steps: [
      'Fermez les yeux.',
      'Visualisez le chiffre 100 qui s\'écrit ou se dessine.',
      'Voyez-le s\'effacer lentement.',
      'Visualisez le chiffre 99.',
      'Si une pensée intrusive arrive, revenez doucement au dernier chiffre.'
    ],
    warning: 'Si fermer les yeux augmente l’inconfort ou les images difficiles, gardez-les ouverts et choisissez un repère visuel neutre.',
    imageUrl: '/images/exercises/visual-countdown.svg',
    tags: ['Visualisation', 'Sommeil', 'Mental'],
    supportNeeds: [SupportNeed.Focus, SupportNeed.Sequencing],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'self-hug',
    title: 'Auto-Étreinte (Contenant)',
    description: 'Redéfinir les limites corporelles pour se sentir contenu et en sécurité.',
    situation: [Situation.Stress, Situation.Freeze],
    neurotypes: [NeuroType.ASD, NeuroType.Trauma],
    duration: '1 minute',
    steps: [
      'Croisez les bras.',
      'Placez la main droite sous l\'aisselle gauche.',
      'Placez la main gauche sur l\'épaule droite.',
      'Pressez fermement.',
      'Sentez vos limites : "Je commence ici, je m\'arrête là".'
    ],
    warning: 'Relâchez la pression ou arrêtez si le contact est inconfortable, douloureux ou déclenche une détresse.',
    imageUrl: '/images/exercises/self-hug.svg',
    tags: ['Proprioception', 'Sécurité', 'Toucher'],
    supportNeeds: [SupportNeed.SensoryRegulation, SupportNeed.Recovery],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'pmr-jacobson',
    title: 'Relaxation Musculaire (Jacobson)',
    description: 'Contracter puis relâcher les muscles pour sentir la différence entre tension et détente.',
    situation: [Situation.Stress, Situation.Sleep, Situation.Pain],
    neurotypes: [NeuroType.ADHD, NeuroType.HighSensitivity],
    duration: '5-10 minutes',
    steps: [
      'Serrez fort les poings pendant 5 secondes. Relâchez brusquement.',
      'Haussez les épaules vers les oreilles (5s). Relâchez.',
      'Contractez les fessiers et les jambes (5s). Relâchez.',
      'Sentez la vague de chaleur qui suit le relâchement.'
    ],
    warning: 'Ne contractez pas une zone blessée ou douloureuse. Arrêtez si la pratique augmente la douleur ou provoque des crampes.',
    imageUrl: '/images/exercises/pmr-jacobson.svg',
    tags: ['Corps', 'Détente', 'Sommeil'],
    supportNeeds: [SupportNeed.Recovery, SupportNeed.SensoryRegulation],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'five-minute-launch',
    title: 'Le lancement de cinq minutes',
    description: 'Réduire une tâche à un premier pas minuscule pour rendre le démarrage plus accessible.',
    situation: [Situation.Focus, Situation.Freeze],
    neurotypes: [NeuroType.ADHD],
    duration: '5 minutes',
    steps: ['Choisissez une seule tâche.', 'Écrivez la plus petite action visible.', 'Lancez un minuteur de cinq minutes.', 'À la fin, décidez librement de continuer ou d’arrêter.'],
    tags: ['Démarrage', 'Fonctions exécutives'],
    supportNeeds: [SupportNeed.TaskInitiation, SupportNeed.Focus, SupportNeed.TaskSetup],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'visual-task-strip',
    title: 'Bande de tâches visuelle',
    description: 'Transformer une séquence en quelques cartes visibles et faciles à suivre.',
    situation: [Situation.Focus],
    neurotypes: [NeuroType.ADHD, NeuroType.ASD],
    duration: '5-10 minutes',
    steps: ['Notez trois à cinq étapes.', 'Dessinez une case devant chaque étape.', 'Cachez les étapes suivantes si elles distraient.', 'Cochez une case à la fois.'],
    tags: ['Séquençage', 'Organisation'],
    supportNeeds: [SupportNeed.Sequencing, SupportNeed.Organization, SupportNeed.Predictability],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'sensory-menu',
    title: 'Menu sensoriel personnel',
    description: 'Identifier des options sensorielles agréables ou neutres pour différents moments de la journée.',
    situation: [Situation.Stress, Situation.Focus],
    neurotypes: [NeuroType.ASD, NeuroType.HighSensitivity],
    duration: '10 minutes',
    steps: ['Listez les sons, lumières, textures et mouvements confortables.', 'Classez-les en apaisant, stimulant ou neutre.', 'Choisissez une option facile à garder à portée de main.'],
    tags: ['Sensoriel', 'Préférences'],
    supportNeeds: [SupportNeed.SensoryRegulation, SupportNeed.Recovery, SupportNeed.Predictability],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'communication-card',
    title: 'Carte de communication rapide',
    description: 'Préparer une phrase courte à montrer ou envoyer lorsque parler demande trop d’énergie.',
    situation: [Situation.Stress, Situation.Freeze],
    neurotypes: [NeuroType.ASD],
    duration: '5 minutes',
    steps: ['Choisissez un besoin fréquent.', 'Écrivez une phrase directe et respectueuse.', 'Ajoutez ce qui peut aider maintenant.', 'Gardez la carte dans votre téléphone ou portefeuille.'],
    tags: ['Communication', 'Énergie'],
    supportNeeds: [SupportNeed.Communication, SupportNeed.Recovery, SupportNeed.Predictability],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'reading-window',
    title: 'Fenêtre de lecture',
    description: 'Réduire la quantité de texte visible afin de faciliter le suivi d’une ligne.',
    situation: [Situation.Focus],
    neurotypes: [],
    duration: '2 minutes',
    steps: ['Prenez une feuille opaque.', 'Découpez ou laissez un espace de la hauteur d’une ligne.', 'Déplacez la fenêtre au fil de la lecture.', 'Ajustez la largeur et le contraste selon votre confort.'],
    tags: ['Lecture', 'Visuel'],
    supportNeeds: [SupportNeed.ReadingWriting, SupportNeed.Focus, SupportNeed.Sequencing],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'voice-first-draft',
    title: 'Premier brouillon à la voix',
    description: 'Commencer un texte en le dictant, puis organiser les idées dans un second temps.',
    situation: [Situation.Focus, Situation.Freeze],
    neurotypes: [],
    duration: '5-15 minutes',
    steps: ['Ouvrez la dictée vocale locale de votre appareil.', 'Dites les idées sans les corriger.', 'Relisez seulement après avoir terminé.', 'Organisez le texte en petits paragraphes.'],
    tags: ['Écriture', 'Dictée'],
    supportNeeds: [SupportNeed.ReadingWriting, SupportNeed.TaskInitiation, SupportNeed.WorkingMemory],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'movement-preview',
    title: 'Prévisualiser un mouvement',
    description: 'Décomposer une action physique avant de l’essayer à son propre rythme.',
    situation: [Situation.Focus],
    neurotypes: [],
    duration: '3-5 minutes',
    steps: ['Observez l’espace et retirez les obstacles.', 'Nommez les trois premières étapes.', 'Mimez lentement sans charge.', 'Réalisez l’action et arrêtez si elle devient inconfortable.'],
    tags: ['Mouvement', 'Planification'],
    supportNeeds: [SupportNeed.MotorPlanning, SupportNeed.Sequencing, SupportNeed.TaskSetup],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'launch-pad',
    title: 'Zone de départ',
    description: 'Rassembler au même endroit les objets nécessaires à une routine récurrente.',
    situation: [Situation.Focus],
    neurotypes: [NeuroType.ADHD],
    duration: '10 minutes',
    steps: ['Choisissez une routine fréquente.', 'Rassemblez les objets utiles.', 'Placez-les dans un panier ou une zone visible.', 'Ajoutez une étiquette simple.'],
    tags: ['Organisation', 'Mémoire'],
    supportNeeds: [SupportNeed.TaskSetup, SupportNeed.WorkingMemory, SupportNeed.Organization],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'number-anchor',
    title: 'Ancrage concret des nombres',
    description: 'Relier un nombre abstrait à un objet, un dessin ou une quantité visible.',
    situation: [Situation.Focus, Situation.Stress],
    neurotypes: [],
    duration: '5 minutes',
    steps: ['Choisissez le nombre ou calcul à comprendre.', 'Représentez-le avec des objets ou des points.', 'Regroupez les éléments visuellement.', 'Écrivez ensuite l’opération correspondante.'],
    tags: ['Nombres', 'Visuel'],
    supportNeeds: [SupportNeed.NumberSupport, SupportNeed.Confidence, SupportNeed.Sequencing],
    thanksCount: 0,
    moderationStatus: 'approved'
  },
  {
    id: 'estimate-check',
    title: 'Estimer puis vérifier',
    description: 'Donner d’abord une réponse approximative, puis utiliser un outil pour vérifier sans pression.',
    situation: [Situation.Focus, Situation.Stress],
    neurotypes: [],
    duration: '3 minutes',
    steps: ['Notez une fourchette approximative.', 'Utilisez une calculatrice ou un tableau.', 'Comparez sans qualifier l’estimation de bonne ou mauvaise.', 'Gardez le repère qui vous aidera la prochaine fois.'],
    tags: ['Nombres', 'Confiance'],
    supportNeeds: [SupportNeed.NumberSupport, SupportNeed.Confidence, SupportNeed.Predictability],
    thanksCount: 0,
    moderationStatus: 'approved'
  }
];
